#!/bin/bash

# Startup script for PRISM (Linux/Solaris)

# PRISM home directory
DIR=$1
PRISM_DIR="$DIR/prism-4.4.beta-linux64/"
# Class to run
if [ "$PRISM_MAINCLASS" = "" ]; then
        PRISM_MAINCLASS=demos.grid_world_v1
fi

# Set up CLASSPATH:
# We look in both the top-level and the prism sub-directory
# (currently svn/git repos and downloaded distributions differ in structure)
PRISM_CLASSPATH=classes:"$PRISM_DIR":"$PRISM_DIR"/classes:"$PRISM_DIR"/lib/*

# Set up pointers to libraries
# As above, we look in both the top-level and the prism sub-directory
PRISM_LIB_PATH="$PRISM_DIR"/lib:"$PRISM_DIR"/prism/lib

if [ "$OSTYPE" = "darwin"* ]; then
        export DYLD_LIBRARY_PATH="$PRISM_LIB_PATH"
else
        export LD_LIBRARY_PATH="$PRISM_LIB_PATH"
fi

# Command to launch Java
if [ "$PRISM_JAVA" = "" ]; then
        # On OS X, we want to avoiding calling java from the /usr/bin link
        # since it causes problems with dynamic linking (DYLD_LIBRARY_PATH)
        if [ -x /usr/libexec/java_home ]; then
                PRISM_JAVA=`/usr/libexec/java_home`"/bin/java"
        else
                PRISM_JAVA=java
        fi
fi

# Run PRISM through Java
"$PRISM_JAVA" -Djava.library.path="$PRISM_LIB_PATH" -classpath "$PRISM_CLASSPATH" $PRISM_MAINCLASS $DIR "$@"

